apiVersion: apps/v1beta1
kind: Deployment
metadata:
      name: kubianew1
spec:
    replicas: 1
    template:
       metadata:
             name: kubianew1
             labels:
               app: kubianew1
       spec:
          containers:
          - image: shifalisri0102/my-app:0.1
           
            imagePullPolicy: Always
            name: warfile
          
